### ISSUE TITLE
dotnet-sdk does not build with Net SDK 3.1.102

### ISSUE THREAD

**Issue by jpiquot** [dapr/dotnet-sdk#253]
Hi,

There is a bug in .Net Core SDK 3.1.102. The dapr dotnet SDK will not build.

> 
Error CS0012 :	The type 'PipeWriter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO.Pipelines, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.	Dapr.Actors.AspNetCore	D:\Dev\Audit\Dapr\src\Dapr.Actors.AspNetCore\RouterBuilderExtensions.cs	22	N/A

I added a global.json file to my project to fix my build: 
```
{
    "sdk": {
        "version": "3.1.101"
    }
}
```
[AspNetCore issue 19133](https://github.com/dotnet/aspnetcore/issues/19133)

**Comment by amanbha** [comment]
Fixed with PR https://github.com/dapr/dotnet-sdk/pull/250#merged-event
